//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public string M_num { get; set; }
        public string C_num { get; set; }
        public string P_name { get; set; }
        public Nullable<int> P_price { get; set; }
        public Nullable<int> Amount { get; set; }
        public string P_style { get; set; }
    }
}
