//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Score = new HashSet<Score>();
        }
    
        public int P_num { get; set; }
        public string P_Name { get; set; }
        public int P_Price { get; set; }
        public string P_Description { get; set; }
        public string P_Dimension { get; set; }
        public string P_Image { get; set; }
        public bool P_HasMultipleStyle { get; set; }
        public int PActivity_num { get; set; }
        public Nullable<int> PClassify_num { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Score { get; set; }
        public virtual ProductActivity ProductActivity { get; set; }
        public virtual ProductClassify ProductClassify { get; set; }
    }
}
