//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecondHandProduct
    {
        public int SHP_num { get; set; }
        public string SHP_Name { get; set; }
        public int SHP_Price { get; set; }
        public string SHP_Info { get; set; }
        public string SHP_Img { get; set; }
        public string SHP_SellerName { get; set; }
        public string SHP_SellerPhone { get; set; }
    }
}
